services:
  backend:
    build:
      context: ./backend
    image: scribe/backend
    container_name: scribe-backend
    ports:
      - "3001:3001"
      - "3002:3002"
      - "4000:4000"
    env_file:
      - ./backend/.env
    
  frontend:
    build:
      context: ./frontend
    image: scribe/frontend
    container_name: scribe-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env