services:
  backend:
    build:
      context: ./backend
    image: scribe/backend
    container_name: scribe-backend
    ports:
      - "3001:3001"
      - "3002:3002"
    env_file:
      - ./backend/.env
    networks:
      - scribe-network
    
  frontend:
    build:
      context: ./frontend
    image: scribe/frontend
    container_name: scribe-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - scribe-network

networks:
  scribe-network:
    driver: bridge