services:
  traefik:
    image: traefik:v3.1.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      
      # dashboard
      - "--api.dashboard=true"
      - "--entrypoints.traefik.address=:8080"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
    labels:
      # traefik dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`scribe.dominikkoller.com`)"
      - "traefik.http.routers.traefik.entrypoints=traefik"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.priority=10"
    restart: always

  backend:
    build:
      context: ./backend
    image: scribe/backend
    container_name: scribe-backend
    env_file:
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      
      # route /hocuspocus/ to port 3002
      - "traefik.http.routers.backend-hocuspocus.rule=Host(`scribe.dominikkoller.com`) && PathPrefix(`/hocuspocus`)"
      - "traefik.http.routers.backend-hocuspocus.entrypoints=websecure"
      - "traefik.http.routers.backend-hocuspocus.tls.certresolver=myresolver"
      - "traefik.http.routers.backend-hocuspocus.middlewares=strip-hocuspocus"
      - "traefik.http.routers.backend-hocuspocus.service=backend-hocuspocus-service"
      - "traefik.http.services.backend-hocuspocus-service.loadbalancer.server.port=3002"
      - "traefik.http.middlewares.strip-hocuspocus.stripprefix.prefixes=/hocuspocus"
      - "traefik.http.routers.backend-hocuspocus.priority=10"

      # route /graphql/ to port 4000
      - "traefik.http.routers.backend-graphql.rule=Host(`scribe.dominikkoller.com`) && PathPrefix(`/graphql`)"
      - "traefik.http.routers.backend-graphql.entrypoints=websecure"
      - "traefik.http.routers.backend-graphql.tls.certresolver=myresolver"
      - "traefik.http.routers.backend-graphql.middlewares=strip-graphql"
      - "traefik.http.routers.backend-graphql.service=backend-graphql-service"
      - "traefik.http.services.backend-graphql-service.loadbalancer.server.port=4000"
      - "traefik.http.middlewares.strip-graphql.stripprefix.prefixes=/graphql"
      - "traefik.http.routers.backend-graphql.priority=10"
    
  frontend:
    build:
      context: ./frontend
    image: scribe/frontend
    container_name: scribe-frontend
    env_file:
      - ./frontend/.env
    labels:
      - "traefik.enable=true"
      
      # route / to port 3000
      - "traefik.http.routers.frontend.rule=Host(`scribe.dominikkoller.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
